FROM public.ecr.aws/lambda/python:3.11

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy the code
COPY cleaner_service.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD [ "cleaner_service.lambda_handler" ]